
package examples.webservices.hello_world.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HelloWorldService", targetNamespace = "http://hello_world.webservices.examples/", wsdlLocation = "http://localhost:7001/HelloWorldImpl/HelloWorldService?WSDL")
public class HelloWorldService
    extends Service
{

    private final static URL HELLOWORLDSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(examples.webservices.hello_world.client.HelloWorldService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = examples.webservices.hello_world.client.HelloWorldService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:7001/HelloWorldImpl/HelloWorldService?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:7001/HelloWorldImpl/HelloWorldService?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HELLOWORLDSERVICE_WSDL_LOCATION = url;
    }

    public HelloWorldService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldService() {
        super(HELLOWORLDSERVICE_WSDL_LOCATION, new QName("http://hello_world.webservices.examples/", "HelloWorldService"));
    }

    /**
     * 
     * @return
     *     returns HelloWorldPortType
     */
    @WebEndpoint(name = "HelloWorldPortTypePort")
    public HelloWorldPortType getHelloWorldPortTypePort() {
        return super.getPort(new QName("http://hello_world.webservices.examples/", "HelloWorldPortTypePort"), HelloWorldPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldPortType
     */
    @WebEndpoint(name = "HelloWorldPortTypePort")
    public HelloWorldPortType getHelloWorldPortTypePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://hello_world.webservices.examples/", "HelloWorldPortTypePort"), HelloWorldPortType.class, features);
    }

}
